api/urls.py
from django.urls import path, re_path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions
from rest_framework.routers import SimpleRouter
from api import views

schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

router = SimpleRouter()
router.register('courses', views.CourseViewSet, 'courses')

app_name = 'api'
urlpatterns = [
    path('test/', views.test_api_view, name='test'),
    *router.urls,
    re_path('swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc')
]

course/urls.py
from django.urls import path, re_path
from course import views

app_name = 'course'
urlpatterns = [
    path('courses/', views.CourseListView.as_view(), name='course-list'),
    # path('course/<int:pk>', views.CourseDetailView.as_view(), name='course-detail')  # nice
    re_path(r'^course/(?P<pk>[0-9]+)/$', views.CourseDetailView.as_view(), name='course-detail') # trash

]

online_education/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from online_education import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('jet/', include('jet.urls', 'jet')),
    path('api/', include('api.urls', 'api')),
    path('', include('main.urls')),
    path('course/', include('course.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

course/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from main.models import BaseModel, Person, PersonCreator


class UnderComment(BaseModel):
    user = models.ForeignKey(Person, models.CASCADE)
    comment_message = models.TextField(null=False)


class Comment(BaseModel):
    user = models.ForeignKey(Person, models.CASCADE)
    comment_message = models.TextField(null=False)
    under_comm = models.ForeignKey(UnderComment, models.CASCADE, null=True, blank=True)


class UnderFeedback(BaseModel):
    user = models.ForeignKey(Person, models.CASCADE)
    comment = models.TextField(null=False)


class Feedback(BaseModel):
    user = models.ForeignKey(Person, on_delete=models.CASCADE)
    comment = models.TextField(null=False)
    validators = models.FloatField(validators=[MaxValueValidator(1), MinValueValidator(5)])
    under_feed = models.ForeignKey(UnderFeedback, on_delete=models.CASCADE)


class Course(BaseModel):
    title = models.CharField(max_length=200, null=False)
    description = models.TextField(null=False)
    creator = models.ManyToManyRel(PersonCreator, to=models.Model)  # нужна еще возможность добавлять курс от школы
    participant = models.ManyToManyRel(Person, to=models.Model)
    image = models.ImageField(upload_to='img/course', null=True, blank=True)
    feedback = models.ForeignKey(Feedback, on_delete=models.CASCADE, null=True, blank=True)


class Task(BaseModel):
    title = models.CharField(max_length=300, null=False)
    position = models.IntegerField()
    description = models.TextField(max_length=300, null=False)
    # type_of_task = models.TextChoices('Ответ с выборки', 'Ответ текстовый',
    # 'Без задания', 'С проверкой преподоввателя')
    count_of_sample = models.IntegerField(default=999, null=False)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, null=True, blank=True)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, null=True, blank=True)


class ScoreRating(BaseModel):
    user = models.ManyToManyRel(Person, to=models.Model)
    score = models.IntegerField(default=0, editable=False, blank=True)
    course = models.ManyToManyRel(Course, to=models.Model)

course/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from course.models import Course


class CourseListView(ListView):
    template_name = 'course/course-list.html'
    model = Course
    paginate_by = 20


class CourseDetailView(DetailView):
    template_name = 'course/course-detail.html'
    model = Course

course/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block bootstrap_header %}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
              crossorigin="anonymous">
        <link rel="canonical" href="https://getbootstrap.com/docs/4.1/examples/sticky-footer-navbar/">
    {% endblock bootstrap_header %}
    {% load static %}
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <link rel="stylesheet" href="{% static "css/sticky-footer-navbar.css" %}">
    {% block extra_head %}
    {% endblock extra_head %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-secondary ">
    <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link text-white" href="{% url 'index' %}"><h5>Home</h5></a>
            </li>
             <li class="nav-item">
                <a class="nav-link text-white" href="{% url 'course:course-list' %}">Courses</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-white" href="{% url 'index' %}">About Us</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-white" href="{% url 'index' %}">Contact</a>
            </li>
        </ul>
        <span class="navbar-text">
            {% if user.is_authenticated %}
                <a class="nav-link text-white" href="{% url 'profile-create' %}">Profile<span class="sr-only">(current)</span></a>
                <a class="nav-link text-white" href="{% url 'logout' %}">Log out<span class="sr-only">(current)</span></a>
            {% else %}
                <a class="nav-link text-white" href="{% url 'login' %}">Log in<span class="sr-only">(current)</span></a>
            {% endif %}
        </span>
    </div>

</nav>
<div class="d-flex align-items-center justify-content-center p-3 mb-2 bg-light block-content">
    {% block content %}
    {% endblock content %}
</div>
</body>
<footer class="footer">
  <div class="container">
    <p class="text-muted">SmartClass create by django</p>
  </div>
</footer>